/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_vistas_;

import java.awt.event.ItemEvent;

/**
 *
 * @author J
 */
public class Frm_Consulta_Renta extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Consulta_Renta
     */
    public Frm_Consulta_Renta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_idRenta = new javax.swing.JLabel();
        ct_idCliente = new javax.swing.JTextField();
        lb_HoraInicio = new javax.swing.JLabel();
        ct_HoraInicio = new javax.swing.JTextField();
        lb_HoraFinal = new javax.swing.JLabel();
        ct_FechaRenta = new javax.swing.JTextField();
        lb_idCliente = new javax.swing.JLabel();
        lb_FechaRenta = new javax.swing.JLabel();
        ct_idVehiculo = new javax.swing.JTextField();
        lb_idVehiculo = new javax.swing.JLabel();
        cmb_idRenta = new javax.swing.JComboBox<>();
        ct_HoraFinal1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Rentas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 686));

        lb_idRenta.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idRenta.setText("Id Renta:");

        ct_idCliente.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_idCliente.setFocusable(false);

        lb_HoraInicio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_HoraInicio.setText("Hora de Inicio:");

        ct_HoraInicio.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_HoraInicio.setFocusable(false);

        lb_HoraFinal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_HoraFinal.setText("Hora Final: ");

        ct_FechaRenta.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_FechaRenta.setFocusable(false);

        lb_idCliente.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idCliente.setText("Id Cliente:");

        lb_FechaRenta.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_FechaRenta.setText("Fecha de Renta:");

        ct_idVehiculo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_idVehiculo.setFocusable(false);

        lb_idVehiculo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idVehiculo.setText("Id Vehiculo:");

        cmb_idRenta.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmb_idRenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idRentaItemStateChanged(evt);
            }
        });

        ct_HoraFinal1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_HoraFinal1.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_idVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idVehiculo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_idCliente)
                        .addGap(12, 12, 12)
                        .addComponent(ct_idCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_idRenta)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_idRenta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_HoraInicio)
                        .addGap(18, 18, 18)
                        .addComponent(ct_HoraInicio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_HoraFinal)
                        .addGap(18, 18, 18)
                        .addComponent(ct_HoraFinal1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_FechaRenta)
                        .addGap(18, 18, 18)
                        .addComponent(ct_FechaRenta, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idRenta)
                    .addComponent(cmb_idRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idVehiculo)
                    .addComponent(ct_idVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idCliente)
                    .addComponent(ct_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HoraInicio)
                    .addComponent(ct_HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HoraFinal)
                    .addComponent(ct_HoraFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_FechaRenta)
                    .addComponent(ct_FechaRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_idRentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idRentaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int fila = cmb_idRenta.getSelectedIndex();
            if (fila >= 0 && fila < Dtm.getRowCount()) {
                try {
                 //variables de la base de datos usando: txt_titulo.setText(Dtm.getValueAt(fila, 1) != null ? Dtm.getValueAt(fila, 1).toString() : "");
                } catch (Exception e) {
                    System.out.println("Error al cargar datos: " + e.getMessage());
                    //limpiar
                }
            }
        }
    }//GEN-LAST:event_cmb_idRentaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Consulta_Renta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_idRenta;
    private javax.swing.JTextField ct_FechaRenta;
    private javax.swing.JTextField ct_HoraFinal1;
    private javax.swing.JTextField ct_HoraInicio;
    private javax.swing.JTextField ct_idCliente;
    private javax.swing.JTextField ct_idVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_FechaRenta;
    private javax.swing.JLabel lb_HoraFinal;
    private javax.swing.JLabel lb_HoraInicio;
    private javax.swing.JLabel lb_idCliente;
    private javax.swing.JLabel lb_idRenta;
    private javax.swing.JLabel lb_idVehiculo;
    // End of variables declaration//GEN-END:variables
}
