/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_vistas_;

import java.awt.event.ItemEvent;

/**
 *
 * @author J
 */
public class Frm_Consulta_Vehiculos extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Consulta_Vehiculos
     */
    public Frm_Consulta_Vehiculos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_Color = new javax.swing.JLabel();
        ct_Color = new javax.swing.JTextField();
        ct_Precio = new javax.swing.JTextField();
        lb_Precio = new javax.swing.JLabel();
        ct_Modelo = new javax.swing.JTextField();
        lb_Modelo = new javax.swing.JLabel();
        lb_idVehiculo = new javax.swing.JLabel();
        lb_Marca = new javax.swing.JLabel();
        ct_Marca = new javax.swing.JTextField();
        lb_Cilindrada = new javax.swing.JLabel();
        ct_Cilindrada = new javax.swing.JTextField();
        lb_noLLantas = new javax.swing.JLabel();
        lb_velocidadMaxima = new javax.swing.JLabel();
        ct_velocidadMaxima = new javax.swing.JTextField();
        ct_noRuedas = new javax.swing.JLabel();
        lb_materialBota = new javax.swing.JLabel();
        ct_materialBota = new javax.swing.JTextField();
        lb_Tipo = new javax.swing.JLabel();
        ct_TipoVehiculo = new javax.swing.JTextField();
        lb_tipoVehiculo = new javax.swing.JLabel();
        cmb_idVehiculo = new javax.swing.JComboBox<>();
        ct_Tipo = new javax.swing.JTextField();
        lb_Año = new javax.swing.JLabel();
        ct_NoLlantas = new javax.swing.JTextField();
        ct_NoRuedas = new javax.swing.JTextField();
        ct_Año = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Vehiculos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N

        lb_Color.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Color.setText("Color:");

        ct_Color.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Color.setFocusable(false);

        ct_Precio.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Precio.setFocusable(false);

        lb_Precio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Precio.setText("Precio:");

        ct_Modelo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Modelo.setFocusable(false);

        lb_Modelo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Modelo.setText("Modelo:");

        lb_idVehiculo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idVehiculo.setText("Id Vehículo:");

        lb_Marca.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Marca.setText("Marca:");

        ct_Marca.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Marca.setFocusable(false);

        lb_Cilindrada.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Cilindrada.setText("Cilindrada:");

        ct_Cilindrada.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Cilindrada.setFocusable(false);

        lb_noLLantas.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_noLLantas.setText("No LLantas:");

        lb_velocidadMaxima.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_velocidadMaxima.setText("Velocidad Máxima:");

        ct_velocidadMaxima.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_velocidadMaxima.setFocusable(false);

        ct_noRuedas.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ct_noRuedas.setText("No Ruedas:");

        lb_materialBota.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_materialBota.setText("Material Bota:");

        ct_materialBota.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_materialBota.setFocusable(false);

        lb_Tipo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Tipo.setText("Tipo:");

        ct_TipoVehiculo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_TipoVehiculo.setFocusable(false);

        lb_tipoVehiculo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_tipoVehiculo.setText("Tipo Vehiculo:");

        cmb_idVehiculo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmb_idVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idVehiculoItemStateChanged(evt);
            }
        });

        ct_Tipo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Tipo.setFocusable(false);

        lb_Año.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Año.setText("Año:");

        ct_NoLlantas.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_NoLlantas.setFocusable(false);

        ct_NoRuedas.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_NoRuedas.setFocusable(false);

        ct_Año.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Año.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Tipo)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Tipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Cilindrada)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Cilindrada))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_tipoVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(ct_TipoVehiculo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_idVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_idVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_Modelo)
                            .addComponent(lb_Precio)
                            .addComponent(lb_Color))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ct_Modelo)
                            .addComponent(ct_Precio)
                            .addComponent(ct_Marca)
                            .addComponent(ct_Color)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_velocidadMaxima)
                        .addGap(18, 18, 18)
                        .addComponent(ct_velocidadMaxima, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_materialBota)
                        .addGap(18, 18, 18)
                        .addComponent(ct_materialBota))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_noLLantas)
                        .addGap(18, 18, 18)
                        .addComponent(ct_NoLlantas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Marca)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ct_noRuedas)
                        .addGap(18, 18, 18)
                        .addComponent(ct_NoRuedas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Año)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Año)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idVehiculo)
                    .addComponent(cmb_idVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Modelo)
                    .addComponent(ct_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Precio)
                    .addComponent(ct_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Marca)
                    .addComponent(ct_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Año)
                    .addComponent(ct_Año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Color)
                    .addComponent(ct_Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipoVehiculo)
                    .addComponent(ct_TipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Cilindrada)
                    .addComponent(ct_Cilindrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Tipo)
                    .addComponent(ct_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_noLLantas)
                    .addComponent(ct_NoLlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_materialBota)
                    .addComponent(ct_materialBota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_velocidadMaxima)
                    .addComponent(ct_velocidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_noRuedas)
                    .addComponent(ct_NoRuedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_idVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idVehiculoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int fila = cmb_idVehiculo.getSelectedIndex();
            if (fila >= 0 && fila < Dtm.getRowCount()) {
                try {
                 //variables de la base de datos usando: txt_titulo.setText(Dtm.getValueAt(fila, 1) != null ? Dtm.getValueAt(fila, 1).toString() : "");
                } catch (Exception e) {
                    System.out.println("Error al cargar datos: " + e.getMessage());
                    //limpiar
                }
            }
        }
    }//GEN-LAST:event_cmb_idVehiculoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Consulta_Vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_idVehiculo;
    private javax.swing.JTextField ct_Año;
    private javax.swing.JTextField ct_Cilindrada;
    private javax.swing.JTextField ct_Color;
    private javax.swing.JTextField ct_Marca;
    private javax.swing.JTextField ct_Modelo;
    private javax.swing.JTextField ct_NoLlantas;
    private javax.swing.JTextField ct_NoRuedas;
    private javax.swing.JTextField ct_Precio;
    private javax.swing.JTextField ct_Tipo;
    private javax.swing.JTextField ct_TipoVehiculo;
    private javax.swing.JTextField ct_materialBota;
    private javax.swing.JLabel ct_noRuedas;
    private javax.swing.JTextField ct_velocidadMaxima;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Año;
    private javax.swing.JLabel lb_Cilindrada;
    private javax.swing.JLabel lb_Color;
    private javax.swing.JLabel lb_Marca;
    private javax.swing.JLabel lb_Modelo;
    private javax.swing.JLabel lb_Precio;
    private javax.swing.JLabel lb_Tipo;
    private javax.swing.JLabel lb_idVehiculo;
    private javax.swing.JLabel lb_materialBota;
    private javax.swing.JLabel lb_noLLantas;
    private javax.swing.JLabel lb_tipoVehiculo;
    private javax.swing.JLabel lb_velocidadMaxima;
    // End of variables declaration//GEN-END:variables
}
