/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pck_vistas_;

import java.awt.event.ItemEvent;
import Pck_Datos_.ClientesPG_DB;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J
 */
public class Frm_Consulta_Clientes extends javax.swing.JFrame {
    private final ClientesPG_DB cliente;
    DefaultTableModel Dtm = new DefaultTableModel();

    /**
     * Creates new form Frm_Consulta_Clientes
     */
    public Frm_Consulta_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        cliente = new ClientesPG_DB();
        Dtm = cliente.getDatosCleinte();
        for(int i= 0; i<Dtm.getRowCount(); i++){
            cmb_idCliente.addItem(Dtm.getValueAt(i, 0).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_idCliente = new javax.swing.JLabel();
        ct_Tipo = new javax.swing.JTextField();
        lb_Nombre = new javax.swing.JLabel();
        ct_Nombre = new javax.swing.JTextField();
        lb_Direccion = new javax.swing.JLabel();
        ct_Direccion = new javax.swing.JTextField();
        lb_Telefono = new javax.swing.JLabel();
        ct_Telefono = new javax.swing.JTextField();
        lb_Tipo = new javax.swing.JLabel();
        cmb_idCliente = new javax.swing.JComboBox<>();
        lb_Fecha = new javax.swing.JLabel();
        lb_Identificacion = new javax.swing.JLabel();
        ct_Identificacion = new javax.swing.JTextField();
        ct_Fecha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consulta de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 686));

        lb_idCliente.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idCliente.setText("Id Cliente:");

        ct_Tipo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Tipo.setFocusable(false);

        lb_Nombre.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Nombre.setText("Nombre:");

        ct_Nombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Nombre.setFocusable(false);

        lb_Direccion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Direccion.setText("Direccion:");

        ct_Direccion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Direccion.setFocusable(false);

        lb_Telefono.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Telefono.setText("Telefono:");

        ct_Telefono.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Telefono.setFocusable(false);

        lb_Tipo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Tipo.setText("Tipo:");

        cmb_idCliente.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmb_idCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_idClienteItemStateChanged(evt);
            }
        });

        lb_Fecha.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Fecha.setText("Fecha de nacimiento");

        lb_Identificacion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Identificacion.setText("Identificacion:");

        ct_Identificacion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Identificacion.setFocusable(false);

        ct_Fecha.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        ct_Fecha.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_idCliente)
                        .addGap(18, 18, 18)
                        .addComponent(cmb_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Nombre)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Nombre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Direccion)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Direccion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Identificacion)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Identificacion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Telefono)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Telefono))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Tipo)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Tipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Fecha)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Fecha)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idCliente)
                    .addComponent(cmb_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Nombre)
                    .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Direccion)
                    .addComponent(ct_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Identificacion)
                    .addComponent(ct_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Telefono)
                    .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Tipo)
                    .addComponent(ct_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Fecha)
                    .addComponent(ct_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_idClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_idClienteItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int fila = cmb_idCliente.getSelectedIndex();
            if (fila >= 0 && fila < Dtm.getRowCount()) {
                try {
                 //variables de la base de datos usando: txt_titulo.setText(Dtm.getValueAt(fila, 1) != null ? Dtm.getValueAt(fila, 1).toString() : "");
                    ct_Nombre.setText(Dtm.getValueAt(fila, 1).toString());
                    ct_Direccion.setText(Dtm.getValueAt(fila, 2).toString());
                    ct_Identificacion.setText(Dtm.getValueAt(fila, 3).toString());
                    ct_Telefono.setText(Dtm.getValueAt(fila, 4).toString());
                    ct_Tipo.setText(Dtm.getValueAt(fila, 5).toString());
                    ct_Fecha.setText(Dtm.getValueAt(fila, 6).toString());
                } catch (Exception e) {
                    System.out.println("Error al cargar datos: " + e.getMessage());
                    //limpiar
                }
            }
        }
    }//GEN-LAST:event_cmb_idClienteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Consulta_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Consulta_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_idCliente;
    private javax.swing.JTextField ct_Direccion;
    private javax.swing.JTextField ct_Fecha;
    private javax.swing.JTextField ct_Identificacion;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JTextField ct_Telefono;
    private javax.swing.JTextField ct_Tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lb_Direccion;
    private javax.swing.JLabel lb_Fecha;
    private javax.swing.JLabel lb_Identificacion;
    private javax.swing.JLabel lb_Nombre;
    private javax.swing.JLabel lb_Telefono;
    private javax.swing.JLabel lb_Tipo;
    private javax.swing.JLabel lb_idCliente;
    // End of variables declaration//GEN-END:variables
}
