package pck_vistas_;

import Pck_Examen.Hora;
import javax.swing.JOptionPane;

public class Frm_Menu_Renta extends javax.swing.JFrame {

    public Frm_Menu_Renta() {
        initComponents();
    }

    private void listar() {
//        tbl_Rentas.setModel(PDB.getDatos());
    }

    private void limpiar() {
        ct_HoraFinal.setText("");
        ct_HoraInicio.setText("");
        ct_idCliente.setText("");
        ct_idRenta.setText("");
        ct_idVehiculo.setText("");
        
    }

    private Hora validarHora(String horaStr, String campoNombre) {
        String[] partes = horaStr.split(":");
        if (partes.length != 2) {
            JOptionPane.showMessageDialog(null, "El formato de la " + campoNombre + " debe ser en formato HH:MM",
                    "Warning", 2);
            return null;
        }
        try {
            int hora = Integer.parseInt(partes[0].trim());
            int minuto = Integer.parseInt(partes[1].trim());
            Hora horaObj = new Hora(hora, minuto);

            if (horaObj.horaCorrecta()) {
                return horaObj;
            } else {
                return null;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null,
                    "La hora debe contener valores numéricos para horas y minutos en formato HH:MM",
                    "Warning", 2);
            return null;
        }
    }

    private void aregar_actualizar(boolean agregar) {
        int idRenta = 0, idVehiculo = 0, idCliente = 0, res = 0;
        boolean valido = false;

        try {
            idRenta = Integer.parseInt(ct_idRenta.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID de la renta debe ser numérico",
                    "Warning", 2);
            ct_idRenta.setText("");
            valido = false;
        }

        try {
            idVehiculo = Integer.parseInt(ct_idVehiculo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID del vehiculo debe ser numérico",
                    "Warning", 2);
            ct_idVehiculo.setText("");
            valido = false;
        }

        try {
            idCliente = Integer.parseInt(ct_idCliente.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID Cliente debe ser numérico",
                    "Warning", 2);
            ct_idCliente.setText("");
            valido = false;
        }

        if (!valido) {
            return;
        }

        Hora horaInicio = validarHora(ct_HoraInicio.getText(), "Hora de Inicio");
        if (horaInicio == null) {
            ct_HoraInicio.setText("");
            valido = false;
        }

        Hora horaFinal = validarHora(ct_HoraFinal.getText(), "Hora Final");
        if (horaFinal == null) {
            ct_HoraFinal.setText("");
            valido = true;
        }

        if (!valido) {
            return;
        }

        if (horaFinal.esMenorQue(horaInicio) || horaFinal.getHora().equals(horaInicio.getHora())) {
            JOptionPane.showMessageDialog(null, "La Hora Final (" + horaFinal.getHora() + ") no puede ser menor o igual a la Hora de Inicio (" + horaInicio.getHora() + ").",
                     "Error de Renta", 2);
            valido = false;
        }

        if (!valido) {
            return;
        }

        if (valido && agregar) {
//            res = PDB.agregarRegistro(idRenta, idVehiculo, idCliente, FechaRenta, HoraInicio, HoraFinal);
        } else if (valido && !agregar) {
//            res = PDB.agregarRegistro(idRenta, idVehiculo, idCliente, FechaRenta, HoraInicio, HoraFinal);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor conteste todos campos o verifique que sean datos validos",
                    "Error de carga de datos", 0);
        }

        if (res > 0) {
//            this.listar();
//            this.limpiar();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ct_idCliente = new javax.swing.JTextField();
        lb_idCliente = new javax.swing.JLabel();
        lb_idRenta = new javax.swing.JLabel();
        ct_idRenta = new javax.swing.JTextField();
        lb_idVehiculo = new javax.swing.JLabel();
        ct_idVehiculo = new javax.swing.JTextField();
        lb_FechaRenta = new javax.swing.JLabel();
        lb_HoraFinal = new javax.swing.JLabel();
        ct_HoraInicio = new javax.swing.JTextField();
        lb_HoraInicio = new javax.swing.JLabel();
        ct_HoraFinal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cmb_opcionesR = new javax.swing.JComboBox<>();
        ct_parametroR = new javax.swing.JTextField();
        btn_buscarR = new javax.swing.JButton();
        btn_resetR = new javax.swing.JButton();
        btn_Consultar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Rentas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de Rentas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N

        ct_idCliente.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_idCliente.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idCliente.setText("Id Cliente:");

        lb_idRenta.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idRenta.setText("Id Renta:");

        ct_idRenta.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_idVehiculo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idVehiculo.setText("Id Vehiculo:");

        ct_idVehiculo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_FechaRenta.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_FechaRenta.setText("Fecha de Renta:");

        lb_HoraFinal.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_HoraFinal.setText("Hora Final: ");

        ct_HoraInicio.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_HoraInicio.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_HoraInicio.setText("Hora de Inicio:");

        ct_HoraFinal.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb_idRenta)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_idVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(lb_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ct_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lb_HoraInicio)
                                .addGap(18, 18, 18)
                                .addComponent(ct_HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(lb_HoraFinal)
                                .addGap(18, 18, 18)
                                .addComponent(ct_HoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(lb_FechaRenta)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idRenta)
                    .addComponent(ct_idRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_idVehiculo)
                    .addComponent(ct_idVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_idCliente)
                    .addComponent(ct_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_HoraInicio)
                    .addComponent(ct_HoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_HoraFinal)
                    .addComponent(ct_HoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_FechaRenta)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        cmb_opcionesR.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        cmb_opcionesR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Venta", "Id Cliente", "Id Vehiculo" }));
        cmb_opcionesR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_opcionesRActionPerformed(evt);
            }
        });

        ct_parametroR.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        btn_buscarR.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_buscarR.setText("Buscar");

        btn_resetR.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_resetR.setText("Reset");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_opcionesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ct_parametroR, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_buscarR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_resetR)
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_opcionesR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_parametroR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarR)
                    .addComponent(btn_resetR))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_Consultar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Consultar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Consultar.setText("Consultar");

        btn_Eliminar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Eliminar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");

        btn_Actualizar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Actualizar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btn_Agregar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Agregar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        tbl_Rentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Rentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_RentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Rentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Agregar)
                        .addGap(48, 48, 48)
                        .addComponent(btn_Actualizar)
                        .addGap(59, 59, 59)
                        .addComponent(btn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Consultar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_opcionesRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_opcionesRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_opcionesRActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed

    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed

    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void tbl_RentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_RentasMouseClicked
        int fila = tbl_Rentas.getSelectedRow();
        ct_idRenta.setText(tbl_Rentas.getValueAt(fila, 0).toString());
        ct_idVehiculo.setText(tbl_Rentas.getValueAt(fila, 1).toString());
        ct_idCliente.setText(tbl_Rentas.getValueAt(fila, 2).toString());
        //aqui va el Jdt_Fecha
        ct_HoraInicio.setText(tbl_Rentas.getValueAt(fila, 3).toString());
        ct_HoraFinal.setText(tbl_Rentas.getValueAt(fila, 4).toString());
    }//GEN-LAST:event_tbl_RentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Renta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu_Renta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_buscarR;
    private javax.swing.JButton btn_resetR;
    private javax.swing.JComboBox<String> cmb_opcionesR;
    private javax.swing.JTextField ct_HoraFinal;
    private javax.swing.JTextField ct_HoraInicio;
    private javax.swing.JTextField ct_idCliente;
    private javax.swing.JTextField ct_idRenta;
    private javax.swing.JTextField ct_idVehiculo;
    private javax.swing.JTextField ct_parametroR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_FechaRenta;
    private javax.swing.JLabel lb_HoraFinal;
    private javax.swing.JLabel lb_HoraInicio;
    private javax.swing.JLabel lb_idCliente;
    private javax.swing.JLabel lb_idRenta;
    private javax.swing.JLabel lb_idVehiculo;
    private javax.swing.JTable tbl_Rentas;
    // End of variables declaration//GEN-END:variables
}
