//
//José Luis González Flor
//
package pck_vistas_;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import Pck_Datos_.ClientesPG_DB;
import java.text.ParseException;


public class Frm_Menu_Clientes extends javax.swing.JFrame {
    private final ClientesPG_DB CDB;
    
    public Frm_Menu_Clientes() {
        initComponents();
        CDB = new ClientesPG_DB();
        this.setLocationRelativeTo(null);
        this.listar();
    }
    
    private void listar(){
        tbl_Clientes.setModel(CDB.getDatosCleinte());
    }
    
    private void limpiar(){
        ct_idCliente.setText("");
        ct_Telefono.setText("");
        ct_Nombre.setText("");
        ct_Identificacion.setText("");
        ct_Direccion.setText("");
        cmb_Tipo.setSelectedIndex(-1);
        jdt_Fecha.setDate(null);
    }
    
    private void agregar_actualizar(boolean agregar) {
        String id, nombre, direccion, identificacion, telefono, tipo = null;
        int res = 0;
        boolean valido = true;

        id = ct_idCliente.getText();
        if (id == null || id.isBlank() || !id.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9 ]+$")) {
            JOptionPane.showMessageDialog(null,
                    "No corresponde a un id válido.", "Warning", 2);
            ct_idCliente.setText("");
            valido = false;
        }

        nombre = ct_Nombre.getText();
        if (nombre == null || nombre.isBlank() || !nombre.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9.,:;!?()\"'\\- ]+$")) {
            JOptionPane.showMessageDialog(null,
                    "No corresponde a un nombre válido.", "Warning", 2);
            ct_Nombre.setText("");
            valido = false;
        }
        
        direccion = ct_Direccion.getText();
        if (direccion == null || direccion.isBlank() || !direccion.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9 #.,\\-/]+$")) {
            JOptionPane.showMessageDialog(null,
                    "No corresponde a una dirección válida.", "Warning", 2);
            ct_Direccion.setText("");
            valido = false;
        }
        
        identificacion = ct_Identificacion.getText();
        if (identificacion == null || identificacion.isBlank() || !identificacion.matches("^[A-Za-zÁÉÍÓÚáéíóúÑñ0-9 #.,\\-/]+$")) {
            JOptionPane.showMessageDialog(null,
                    "No corresponde a una identificacion válida.", "Warning", 2);
            ct_Identificacion.setText("");
            valido = false;
        }
        
        telefono = ct_Telefono.getText();
        if (telefono == null || telefono.isBlank() || !telefono.matches("^[0-9 +()\\-]+$")) {
            JOptionPane.showMessageDialog(null,
                    "No corresponde a un teléfono válido.", "Warning", 2);
            ct_Telefono.setText("");
            valido = false;
        }
        
        if(cmb_Tipo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "El campo tipo esta vacio", "Error", 2);
            valido = false;
        }else{
            tipo = cmb_Tipo.getSelectedItem().toString();
        }
        
        java.sql.Date fechaE = null;
        Date fE = jdt_Fecha.getDate();
        if(fE == null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha de estreno", "Error", 2);
            valido = false;
        }else{
        long dE = fE.getTime();
        fechaE = new java.sql.Date(dE);
        }

        if(valido && agregar){
        res = CDB.agregarCliente(id, nombre, direccion, identificacion, telefono, tipo, fechaE);
        this.listar();
        this.limpiar();
         JOptionPane.showMessageDialog(null, "Cliente agregado con exito", "Registro exitoso", 3);
        }else if (valido && !agregar){
                res = CDB.actualizarRegistroCliente(id, nombre, direccion, identificacion, telefono, tipo, fechaE);
                
        }if(res > 0){
            this.listar();
            this.limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "No se puede seguir con el proceso, Todos los datos deben ser válidos", "Error", 2);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_idCliente = new javax.swing.JLabel();
        ct_idCliente = new javax.swing.JTextField();
        lb_Nombre = new javax.swing.JLabel();
        ct_Nombre = new javax.swing.JTextField();
        lb_Direccion = new javax.swing.JLabel();
        ct_Direccion = new javax.swing.JTextField();
        lb_Identificacion = new javax.swing.JLabel();
        ct_Identificacion = new javax.swing.JTextField();
        lb_Tipo = new javax.swing.JLabel();
        cmb_Tipo = new javax.swing.JComboBox<>();
        lb_Telefono = new javax.swing.JLabel();
        ct_Telefono = new javax.swing.JTextField();
        lb_Fecha = new javax.swing.JLabel();
        jdt_Fecha = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        cmb_OpcionesC = new javax.swing.JComboBox<>();
        ct_ParametroC = new javax.swing.JTextField();
        btn_buscarC = new javax.swing.JButton();
        btn_resetC = new javax.swing.JButton();
        btn_Agregar = new javax.swing.JButton();
        btn_Consultar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        tb_Datos = new javax.swing.JScrollPane();
        tbl_Clientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 1, 24))); // NOI18N

        lb_idCliente.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_idCliente.setText("Id Cliente:");

        ct_idCliente.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_Nombre.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Nombre.setText("Nombre:");

        ct_Nombre.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_Direccion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Direccion.setText("Direccion:");

        ct_Direccion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_Identificacion.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Identificacion.setText("Identificacion:");

        ct_Identificacion.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_Tipo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Tipo.setText("Tipo:");

        cmb_Tipo.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        cmb_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Premium" }));

        lb_Telefono.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Telefono.setText("Telefono:");

        ct_Telefono.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        lb_Fecha.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lb_Fecha.setText("Fecha de nacimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_Direccion)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(lb_Identificacion)
                        .addGap(18, 18, 18)
                        .addComponent(ct_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lb_idCliente)
                            .addGap(18, 18, 18)
                            .addComponent(ct_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83)
                            .addComponent(lb_Nombre)
                            .addGap(18, 18, 18)
                            .addComponent(ct_Nombre))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lb_Tipo)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lb_Telefono)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lb_Fecha)
                                    .addGap(18, 18, 18)
                                    .addComponent(jdt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_idCliente)
                    .addComponent(ct_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Nombre)
                    .addComponent(ct_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Direccion)
                    .addComponent(ct_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_Identificacion)
                    .addComponent(ct_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Telefono)
                    .addComponent(ct_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_Tipo)
                        .addComponent(cmb_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_Fecha)
                    .addComponent(jdt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 3, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        cmb_OpcionesC.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        cmb_OpcionesC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id Cliente", "Nombre", " " }));
        cmb_OpcionesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_OpcionesCActionPerformed(evt);
            }
        });

        ct_ParametroC.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        btn_buscarC.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_buscarC.setText("Buscar");
        btn_buscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarCActionPerformed(evt);
            }
        });

        btn_resetC.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_resetC.setText("Reset");
        btn_resetC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_OpcionesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ct_ParametroC, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btn_buscarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_resetC)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_OpcionesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_ParametroC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarC)
                    .addComponent(btn_resetC))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btn_Agregar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Agregar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Consultar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Consultar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Consultar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });

        btn_Eliminar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Eliminar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Actualizar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Actualizar.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        btn_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        tb_Datos.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        tbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ClientesMouseClicked(evt);
            }
        });
        tb_Datos.setViewportView(tbl_Clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb_Datos)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_Actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(btn_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btn_Agregar)
                        .addGap(48, 48, 48)
                        .addComponent(btn_Actualizar)
                        .addGap(59, 59, 59)
                        .addComponent(btn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Consultar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tb_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_OpcionesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_OpcionesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_OpcionesCActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        this.agregar_actualizar(false);
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        this.agregar_actualizar(true);
    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        int res;
        int fila = tbl_Clientes.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro", "Error", 2);
        }else{
            res = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar este cliente?\nNo podra recuperarse despues...","Eliminar un cliente", JOptionPane.YES_NO_OPTION);
            
            if(res == JOptionPane.YES_OPTION){
                res = CDB.eliminarCliente((String)tbl_Clientes.getValueAt(fila, 0));
                this.limpiar();
                this.listar();
            }
        }
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        Frm_Consulta_Clientes frmCC = new Frm_Consulta_Clientes();
        frmCC.setVisible(true);
        this.limpiar();
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void tbl_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ClientesMouseClicked
        int fila = tbl_Clientes.getSelectedRow();
        ct_idCliente.setText(tbl_Clientes.getValueAt(fila, 0).toString());
        ct_Nombre.setText(tbl_Clientes.getValueAt(fila, 1).toString());
        ct_Direccion.setText(tbl_Clientes.getValueAt(fila, 2).toString());
        ct_Identificacion.setText(tbl_Clientes.getValueAt(fila, 3).toString());
        ct_Telefono.setText(tbl_Clientes.getValueAt(fila, 4).toString());
        cmb_Tipo.setSelectedItem(tbl_Clientes.getValueAt(fila, 5).toString());
        String fecha1 = tbl_Clientes.getValueAt(fila, 6).toString();
        Date date1;
        try{
            date1 = new SimpleDateFormat("yyyy-MM-dd").parse(fecha1);
            jdt_Fecha.setDate(date1);
        }catch(ParseException e){
            JOptionPane.showMessageDialog(null,"Error al carga la fecha" + e.getMessage(), "Error", 2);
        }   
    }//GEN-LAST:event_tbl_ClientesMouseClicked

    private void btn_buscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarCActionPerformed
        tbl_Clientes.setModel(CDB.buscarCliente(cmb_OpcionesC.getSelectedIndex(),ct_ParametroC.getText()));
    }//GEN-LAST:event_btn_buscarCActionPerformed

    private void btn_resetCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetCActionPerformed
        this.listar();
        this.limpiar();
    }//GEN-LAST:event_btn_resetCActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.limpiar();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Menu_Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Menu_Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_buscarC;
    private javax.swing.JButton btn_resetC;
    private javax.swing.JComboBox<String> cmb_OpcionesC;
    private javax.swing.JComboBox<String> cmb_Tipo;
    private javax.swing.JTextField ct_Direccion;
    private javax.swing.JTextField ct_Identificacion;
    private javax.swing.JTextField ct_Nombre;
    private javax.swing.JTextField ct_ParametroC;
    private javax.swing.JTextField ct_Telefono;
    private javax.swing.JTextField ct_idCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jdt_Fecha;
    private javax.swing.JLabel lb_Direccion;
    private javax.swing.JLabel lb_Fecha;
    private javax.swing.JLabel lb_Identificacion;
    private javax.swing.JLabel lb_Nombre;
    private javax.swing.JLabel lb_Telefono;
    private javax.swing.JLabel lb_Tipo;
    private javax.swing.JLabel lb_idCliente;
    private javax.swing.JScrollPane tb_Datos;
    private javax.swing.JTable tbl_Clientes;
    // End of variables declaration//GEN-END:variables
}
